# Site settings
name: Casey Hague
email: haguecp@gmail.com
#canonical_url: https://builtthorough.github.io/caseyhague/
keywords: "Software Engineer, Python, Php, SQL, MySQL, Database, Databasing"
skills: "Entry Level Software Engineer in Phoenix, AZ"
baseurl:

# Social networks usernames 
social:
  - title: linkedin
    url: http://linkedin.com/in/caseyhague
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
